version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    working_directory: ~/repo
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
            - run: yarn build
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
            - run: yarn build
workflows:
    branch-build:
      jobs:
        - build:
            filters:
              branches: 
                ignore: 
                  - master
        - deploy:
            filters:
              branches: 
                only: 
                  - master